# Generated by Django 5.2.1 on 2025-06-18 23:03

import apps.users.domain.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.domain.managers.CustomUserManager()),
            ],
        ),
    ]
